import React, { useState } from "react";
import { CheckSquare, Shield, AlertCircle, Edit3, ArrowRight } from "lucide-react";
import { ApplicationPlan } from "../types";

interface PlanApprovalModalProps {
  plan: ApplicationPlan | null;
  onApprove: (modification?: string) => void;
  isOpen: boolean;
}

export const PlanApprovalModal: React.FC<PlanApprovalModalProps> = ({
  plan,
  onApprove,
  isOpen
}) => {
  if (!isOpen || !plan) return null;

  const [modification, setModification] = useState("");
  const [showModInput, setShowModInput] = useState(false);

  const getRiskBadge = (risk: string) => {
    switch (risk) {
      case "HIGH":
        return "bg-rose-950 text-rose-300 border-rose-800";
      case "MEDIUM":
        return "bg-amber-950 text-amber-300 border-amber-800";
      default:
        return "bg-slate-800 text-slate-400 border-slate-700";
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-fadeIn">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-2xl w-full p-6 shadow-2xl flex flex-col max-h-[90vh]">
        <div className="flex items-center justify-between pb-4 border-b border-slate-800">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-xl bg-blue-500/20 text-blue-400 border border-blue-500/30">
              <CheckSquare className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">Application Execution Plan</h3>
              <p className="text-xs text-slate-400">Step-by-step verifiable action sequence generated by ROX</p>
            </div>
          </div>
          <span className="text-xs font-mono px-2.5 py-1 rounded bg-slate-800 text-slate-300 border border-slate-700">
            {plan.steps.length} Steps
          </span>
        </div>

        {/* Steps List */}
        <div className="overflow-y-auto my-4 space-y-2.5 pr-2 flex-1">
          {plan.steps.map((step) => (
            <div
              key={step.step_number}
              className="p-3 bg-slate-950/70 border border-slate-800/80 rounded-xl flex items-start justify-between gap-3 hover:border-slate-700 transition"
            >
              <div className="flex items-start space-x-3">
                <span className="font-mono text-xs font-bold text-blue-400 mt-0.5">
                  #{step.step_number.toString().padStart(2, "0")}
                </span>
                <div>
                  <h4 className="text-sm font-semibold text-white">{step.title}</h4>
                  <p className="text-xs text-slate-400 mt-0.5">{step.description}</p>
                </div>
              </div>

              <span className={`text-[10px] font-mono px-2 py-0.5 rounded border uppercase shrink-0 ${getRiskBadge(step.risk_level)}`}>
                {step.risk_level} Risk
              </span>
            </div>
          ))}
        </div>

        {/* Modifications text area if toggled */}
        {showModInput && (
          <div className="mb-4">
            <label className="text-xs text-slate-300 block mb-1 font-semibold">User Modification Request:</label>
            <input
              type="text"
              value={modification}
              onChange={(e) => setModification(e.target.value)}
              placeholder="e.g. Skip financial section, dry run only..."
              className="w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-blue-500"
            />
          </div>
        )}

        {/* Footer controls */}
        <div className="pt-4 border-t border-slate-800 flex items-center justify-between">
          <button
            onClick={() => setShowModInput(!showModInput)}
            className="text-xs text-slate-400 hover:text-white flex items-center space-x-1.5 transition"
          >
            <Edit3 className="w-3.5 h-3.5" />
            <span>{showModInput ? "Hide Modification" : "Modify Plan"}</span>
          </button>

          <button
            onClick={() => onApprove(modification || undefined)}
            className="px-5 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-semibold text-xs flex items-center space-x-2 shadow-lg shadow-blue-600/30 transition"
          >
            <span>Approve & Authorize Plan</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
};
